In [1]:
import pandas as pd

### Задание 1  
Скачайте с сайта https://grouplens.org/datasets/movielens/ датасет любого размера. Определите какому фильму было выставлено больше всего оценок 5.0.

In [126]:
# создаем df  с еобходимыми данными: читаем файлы, добавляем названия фильмов, оставляем только название фильма и оценки

df_ratings = pd.read_csv('ratings.csv')
df_movies = pd.read_csv('movies.csv')
df = df_ratings.merge(df_movies)
df = df.filter(items = ['rating', 'title'])
df.head()

   rating             title
0     4.0  Toy Story (1995)
1     4.0  Toy Story (1995)
2     4.5  Toy Story (1995)
3     2.5  Toy Story (1995)
4     4.5  Toy Story (1995)

In [132]:
## фильтруем по значению строк рейтинга = 5.0, считаем количество строк по значению столбца с названием фильма

df_rating_5 = df[ df.rating == 5.0 ]
df_rating_5['title'].value_counts().head(1)

Shawshank Redemption, The (1994)    153
Name: title, dtype: int64

### Задание 2  
По данным файла power.csv посчитайте суммарное потребление стран Прибалтики (Латвия, Литва и Эстония) категорий 4, 12 и 21 за период с 2005 по 2010 года. Не учитывайте в расчетах отрицательные значения quantity.

In [150]:
data = pd.read_csv('power.csv')
data.head()

   country  year  quantity  category
0  Austria  1996       5.0         1
1  Austria  1995      17.0         1
2  Belgium  2014       0.0         1
3  Belgium  2013       0.0         1
4  Belgium  2012      35.0         1

In [176]:
#создадим df с помощью фильтров по всем условиям, далее суммируем значения quantity

filtered_data = data[( (data['country']=='Latvia') | (data['country']=='Lithuania')  | (data['country']=='Estonia')) 
                     & ((data['category']==4) | (data['category']==12) | (data['category']==21))  
                     & ((data['year'] > 2005) & (data['year'] < 2010))
                     &  (data['quantity'] > 0)]

value = filtered_data['quantity'].sum()
print('Итоговое значение потребления:', value)

Итоговое значение потребления: 164555.0

### Задание 3  
Выберите страницу любого сайта с табличными данными. Импортируйте таблицы в pandas dataframe.
Примеры страниц (необязательно брать именно эти):

In [191]:
df_1 = pd.read_html('https://www.finanz.ru/valyuty/v-realnom-vremeni', encoding='utf-8')[1]
df_1

,Unnamed: 0,Рубль,Предложение,Спрос,Предыдущее закрытие,%,Абсолютное значение,Время
0,NaN,GBP/RUB,1042287,-,1043911,"-0,16 %",-01625,09:50:00
1,NaN,EUR/RUB,897105,-,898420,"-0,15 %",-01315,09:43:00
2,NaN,USD/RUB,738915,-,740545,"-0,22 %",-01630,09:50:00
3,NaN,JPY/RUB,06767,-,06776,"-0,14 %",-00009,09:50:00
4,NaN,CNY/RUB,114799,-,115044,"-0,21 %",-00246,09:50:00
5,NaN,CHF/RUB,819531,-,821261,"-0,21 %",-01730,09:50:00
6,NaN,Евро,Предложение,Спрос,Предыдущее закрытие,%,Абсолютное значение,Время
7,NaN,EUR/USD,12140,-,12144,"-0,03 %",-00004,09:43:00
8,NaN,EUR/GBP,08606,-,08613,"-0,09 %",-00008,09:43:00
9,NaN,EUR/JPY,1325820,-,1326950,"-0,09 %",-01130,09:43:00
10,NaN,EUR/CHF,10949,-,10948,"0,00 %",00001,09:43:00
11,NaN,Доллар США,Предложение,Спрос,Предыдущее закрытие,%,Абсолютное значение,Время
12,NaN,USD/EUR,08237,-,08235,"0,03 %",00002,09:43:00
13,NaN,USD/GBP,07087,-,07094,"-0,10 %",-00007,09:43:00
14,NaN,USD/JPY,1092030,-,1092850,"-0,08 %",-00820,09:50:00
15,NaN,USD/CHF,09016,-,09016,"0,00 %",00000,09:43:00
16,NaN,Японская иена,Предложение,Спрос,Предыдущее закрытие,%,Абсолютное значение,Время
17,NaN,JPY/EUR (100:1),07500,-,07500,"0,12 %",00000,09:50:00
18,NaN,JPY/GBP,00065,-,00065,"0,02 %",00000,09:50:00
19,NaN,JPY/USD,00092,-,00092,"0,07 %",00000,09:50:00
20,NaN,JPY/CHF (100:1),08300,-,08300,"0,08 %",00000,09:50:00
21,NaN,Фунт стерлингов,Предложение,Спрос,Предыдущее закрытие,%,Абсолютное значение,Время
22,NaN,GBP/USD,14104,-,14097,"0,05 %",00008,09:50:00
23,NaN,GBP/JPY,1540245,-,1540536,"-0,02 %",-00291,09:50:00
24,NaN,GBP/EUR,11620,-,11610,"0,09 %",00010,09:50:00
25,NaN,GBP/CHF,12718,-,12709,"0,08 %",00010,09:50:00
26,NaN,Швейцарский франк,Предложение,Спрос,Предыдущее закрытие,%,Абсолютное значение,Время
27,NaN,GBP/CHF,12718,-,12709,"0,08 %",00010,09:50:00
28,NaN,EUR/CHF,10949,-,10948,"0,00 %",00001,09:43:00
29,NaN,JPY/CHF (100:1),08300,-,08300,"0,08 %",00000,09:50:00
30,NaN,USD/CHF,09016,-,09016,"0,00 %",00000,09:43:00
31,NaN,Украинская гривна,Предложение,Спрос,Предыдущее закрытие,%,Абсолютное значение,Время
32,NaN,EUR/UAH,334570,-,336145,"-0,47 %",-01576,09:50:00
33,NaN,USD/UAH,275627,-,276798,"-0,42 %",-01171,09:49:00
34,NaN,CHF/UAH,305709,-,306968,"-0,41 %",-01259,09:50:00
35,NaN,GBP/UAH,388717,-,390189,"-0,38 %",-01472,09:50:00